# Generated by Django 3.2.9 on 2021-12-12 10:57

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fitness', models.FloatField()),
                ('genes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('abc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=True)),
                ('min_rating', models.IntegerField(blank=True)),
                ('min_perc_rating', models.IntegerField(blank=True)),
                ('initial_iterations', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_iterations', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('crossover_rate', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mutation_rate', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('key', models.CharField(choices=[('C', 'C'), ('C#', 'C#')], default='C', max_length=2)),
                ('pattern', models.CharField(choices=[('I-IV-V-I', 'I-IV-V-I')], default='I-IV-V-I', max_length=20)),
                ('tempo', models.IntegerField(default=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.SmallIntegerField()),
                ('chromosome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evolduo.chromosome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('evolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evolduo.evolution')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('evolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evolduo.evolution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chromosome',
            name='iteration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evolduo.iteration'),
        ),
    ]
