version: '3'

services:
  database:
    image: 'postgres:latest'
    container_name: cherno_db

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
